-- AlterTable
ALTER TABLE `buku` ADD COLUMN `kode_buku` VARCHAR(191) NOT NULL DEFAULT 'TEMP-${id}',
    ADD COLUMN `sinopsis` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('TERSEDIA', 'DIPINJAM', 'DIBLOKIR', 'DIRESERVASI') NOT NULL DEFAULT 'TERSEDIA';
