-- AlterTable
ALTER TABLE `peminjaman` MODIFY `status` ENUM('PENDING', 'DIAJUKAN', 'DISETUJUI', 'DIPINJAM', 'DIPERPANJANG', 'DIKEMBALIKAN', 'DIBATALKAN', 'DITOLAK', 'TERLAMBAT', 'DIBERHENTIKAN', 'MENDEKATI_TANGGAL_PENGEMBALIAN') NOT NULL DEFAULT 'PENDING';
